spring:
  jpa:
    database: POSTGRESQL
    properties.hibernate.temp.use_jdbc_metadata_defaults: false
    hibernate:
      ddl-auto: create
    properties:
  datasource:
    platform: postgres
    url: jdbc:postgresql://192.168.0.246:5432/deposit_service_database
    username: postgres
    password: 671321996
    driver-class-name: org.postgresql.Driver

  rabbitmq:
    port: 5672
    host: 192.168.0.246
    username: guest
    password: guest
    listener:
      direct:
        default-requeue-rejected: true

server:
  port: 9999